---

  - name: transfer apache kafka requirements to cloud host
    copy:
      src: ~/h3/server.properties   # here you can give absolute path also.
      dest: ~/kafka_2.13-2.8.0/config/   # destination directory into which this file will get copied.

  - name: start apache kafka
    ansible.builtin.shell:
      cmd: export KAFKA_OPTS="-Djava.net.preferIPv4Stack=True"; nohup bin/kafka-server-start.sh config/server.properties &
      chdir: ~/kafka_2.13-2.8.0/

  - name: start Consumer1
    ansible.builtin.shell:
      cmd: nohup python3 Consumer.py &
      chdir: ~/app

  - name: start Consumer2
    ansible.builtin.shell:
      cmd: nohup python3 Consumer.py --topic PLUG &
      chdir: ~/app
     
...