# tested w/ 20.04
FROM ubuntu:latest 

ENV KAFKA_OPTS -Djava.net.preferIPv4Stack=True

RUN mkdir /kafka

# install java runtime
RUN apt-get -y update && apt-get install -y default-jre

# transfer, extract, move kafka
COPY kafka_2.13-2.8.0.tgz /
RUN  tar -xzf /kafka_2.13-2.8.0.tgz
RUN  mv kafka_2.13-2.8.0 /kafka



#CMD ["~/kafka/bin/kafka-server-start.sh","~/kafka/config/server.properties"]  will overload w/ k8s