kind: Deployment
apiVersion: apps/v1
metadata:
  name: consumer1
spec:
  selector:
    matchLabels:
      app: consumer1

  template:
    metadata:
      labels:
        app: consumer1
    spec:
      hostname: consumer1
      nodeSelector:
        kubernetes.io/hostname: worker-node
      containers:
        - name: consumer-1
          image: rewhite321/cc:consumer # this is the image in registry accessible
                                     # from all our workers
          imagePullPolicy: Always  # This forces the node to pull the image
          command: ["python3"]
          args: ["/Consumer.py","--topic","MSFT", "--couchdb","http://admin:admin@129.114.26.159:31001/"]  # arguments to run.
      restartPolicy: Always
